version: "3.8"
services:
  download-filenames:
    image: download-filenames
    #build: download-filenames
    depends_on:
      - mq
    volumes:
      - ./download-filenames/.env:/app/.env:ro
      - download-filenames-variables:/app/data
    environment:
      NODE_ENV: production
    deploy:
      restart_policy:
        condition: any
  render:
    image: render
    #build: render
    depends_on:
      - mq
    volumes:
      - ./render/.env:/app/.env:ro
      - render-data:/app/data
    environment:
      NODE_ENV: production
    deploy:
      restart_policy:
        condition: any
  mq:
    image: rabbitmq:3.9
    volumes:
      - queue:/var/lib/rabbitmq
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3
volumes:
  queue:
  download-filenames-variables:
  render-data:
